# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: backend
    type: github
    name: nMagic/test-ci-backend
    endpoint: nMagic
    ref: main
    trigger:
      branches:
        include:
          - main
      tags:
        include:
          - v.*
  - repository: frontend
    type: github
    name: nMagic/test-ci-code
    endpoint: nMagic
    ref: main
    trigger:
      branches:
        include:
          - main
      tags:
        include:
          - v.*

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- checkout: self

- checkout: backend
  fetchTags: true

- checkout: frontend
  fetchTags: true

- bash: ls
  workingDirectory: (Agent.BuildDirectory)
  