name: Replace app versions

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      app:
        description: 'App needing to replace version'
        required: true
        type: choice
        options:
        - ANFISA_BACKEND_VERSION
        - ANFISA_FRONTEND_VERSION
      version:
        description: 'Version to replace'
        required: true
        type: string

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Replace version in template
        run: sed -i 's/${{ inputs.app }}=.*$/${{ inputs.app }}=${{ inputs.version }}/g' ./example.env

      - name: Push commit
        run: |
          git config --global user.name 'Robo'
          git config --global user.email 'Robo@automated.com'
          git commit -am "fix: change version of ${{ inputs.app }}"
          git push
